### ISSUE TITLE
Moving Forwards Again (Discussion)

### ISSUE THREAD

**Issue by HeroesGrave** [Spade-Editor/Spade#75]
First of all, here's the things we need to work on before 1.0:
- [x] **History changes.** First of all, we need to make changes serializable. Then from there it should be reasonably easy to get the rest working.
- [x] **Make sure tools are accurate.** Since we moved some of the tools to Graphics2D, I've noticed a lot of inconsistencies that simply won't do. I think maybe it's time to move away from Graphics2D, and roll out our own drawing tools.
- [x] **Optimisation.** Some things are just too slow to be acceptable. If each of us runs a few profiling tests to see what is going slow, then we can work out what needs to be done.
- [ ] **General Cleanup.** Some things have been more or less hacked together. Where possible, we should clean things up to make it easier to replace them later. Other things feel a bit incomplete.
- [ ] **Nice little touches.** Because these are the things that make a good application great. If you see something that needs a little tweaking or maybe a tiny feature that could benefit the program, go ahead and implement it (Of course making sure that it can be easily removed if it needs to be).

Please comment with any thoughts or discussion you may have.

**Edit: The big changes are going to be part of #76**
